name: WhatsApp Bot Test

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        env:
          MONGODB: mongodb+srv://gamingkolla788_db_user:Kolla123@cluster0.imw2kqu.mongodb.net/?appName=Cluster0
          OWNER_NUM: 94761576618
        run: node index.js
